cmake_minimum_required(VERSION 3.10)
project(AmorGame CXX)
set(CMAKE_CXX_STANDARD 11)
set(SOURCES main.cpp src/map.cpp src/player.cpp src/enemy.cpp src/items.cpp src/game.cpp src/audio.cpp)
add_executable(game ${SOURCES})
target_include_directories(game PRIVATE ${CMAKE_SOURCE_DIR})
if(UNIX)
    target_link_libraries(game pthread m)
endif()
